services:
  mongo:
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: 0.5
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rinha
      MONGO_INITDB_ROOT_PASSWORD: rinha
      MONGO_INITDB_DATABASE: rinha
    networks:
      - rinha-network
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    networks:
      - rinha-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://rinha:rinha@mongo:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: rinha
      ME_CONFIG_MONGODB_ADMINPASSWORD: rinha
      ME_CONFIG_BASICAUTH: false
networks:
  rinha-network:
    driver: bridge