services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
  api01: &api 
    image: ghcr.io/andrelucasti/rinhabackend2025:latest
    environment:
      PAYMENT_PROCESSOR_DEFAULT_BASE_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_BASE_URL: http://payment-processor-fallback:8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - rinha-network
    ports:
      - "8080:8080"
    container_name: rinha-api
    restart: unless-stopped

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
  redis:
    image: redis:latest
    networks:
      - rinha-network
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
networks:
  rinha-network:
    driver: bridge