services:
  redis:
    image: redis:latest
    networks:
      - rinha-network
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
networks:
  rinha-network:
    driver: bridge