server:
  port: ${PORT:9999}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

payment-processor:
  default:
    base-url: ${PAYMENT_PROCESSOR_DEFAULT_BASE_URL:http://localhost:8001}
  fallback:
    base-url: ${PAYMENT_PROCESSOR_FALLBACK_BASE_URL:http://localhost:8002}